// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWQDOMmfKTghuTV1oY5Dv6Ck95HCjx1_4',
    appId: '1:499042276781:web:466e3400736e79179dbd24',
    messagingSenderId: '499042276781',
    projectId: 'moviles-sistemas-2025-2',
    authDomain: 'moviles-sistemas-2025-2.firebaseapp.com',
    storageBucket: 'moviles-sistemas-2025-2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHVtAZA7fGFIUh49_5FLzmBzjMt8jWxfQ',
    appId: '1:499042276781:android:6564f731c0874abe9dbd24',
    messagingSenderId: '499042276781',
    projectId: 'moviles-sistemas-2025-2',
    storageBucket: 'moviles-sistemas-2025-2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzOX3dWYSkbP1X7ATjhvAUB9gxHFArVKg',
    appId: '1:499042276781:ios:8bdb9a3c0f5031c29dbd24',
    messagingSenderId: '499042276781',
    projectId: 'moviles-sistemas-2025-2',
    storageBucket: 'moviles-sistemas-2025-2.firebasestorage.app',
    iosBundleId: 'com.example.pmsn20252',
  );
}
